# **Semi-Guided Practice**

## Objectives

* This is an exercise for the sake of getting reps in whilst still trying to digest the on coming course material

* Using AI to create practice scenarios, with the aim of whittling out the guidance as I progress

* Based on the Iris dataset, handed out in virtual class for practice

* Output
This notebook will contain the ETL process and produce a worked dataset for visualisations and further statistical tests

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Practice_Projects\\pracIris\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Practice_Projects\\pracIris'

# Import block

In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

# Section 1 - Extraction and initial inspection

In [5]:
# Open the csv as a pandas dataframe

df_raw = pd.read_csv("Dataset/Raw/Iris.csv")

df_raw.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [6]:
# Insepcting the initial construction of the data

print("Initial shape:", df_raw.shape)
print('=' * 50)
print("Data types:\n", df_raw.dtypes)
print('=' * 50)
print("missing value count:\n", df_raw.isnull().sum())
print('=' * 50)
print("Duplicates count:\n", df_raw.duplicated().sum())
df_raw.describe()

Initial shape: (150, 6)
==================================================
Data types:
 Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object
==================================================
missing value count:
 Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64
==================================================
Duplicates count:
 0

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

The dataset is pretty clean with no missing values or duplicates. 

This should be really easy to work with.

---

# Section 2 - Transformation

None of the columns datatypes are out of place for the information it's suppposed to be. 

The titles dont't particularly need work. I'm fine with camel case thought there seems to be a dispute on which you should use based on your language.

No missing values and no duplicates with an evenly distributed sample size.

In [7]:
# Showing the distribution of the species in the dataset 
# Here are a few ways to do so

print("Total sample size:", df_raw['Species'].value_counts().sum())

print(df_raw.groupby("Species").size())


df_raw["Species"].value_counts().plot(
    kind="bar",
    title="Species Distribution",
    xlabel="Species",
    ylabel="Count",
    color=["#FF9999", "#66B2FF", "#99FF99"]
)

plt.tight_layout()
plt.show()

# 150 / 3 = 50 samples per species.

Total sample size: 150
Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

* We'll engineer a useful feature, the area of the two plant attributes (sepal and petal), which is a physical feature we can use to attempt identify the subspeices.

In [8]:
# In mwatching sequence
df_raw["SepalArea"] = (df_raw["SepalLengthCm"] * df_raw["SepalWidthCm"])
df_raw["PetalArea"] = (df_raw["PetalLengthCm"] * df_raw["PetalWidthCm"])


df_raw.head(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,SepalArea,PetalArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85,0.28
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28
5,6,5.4,3.9,1.7,0.4,Iris-setosa,21.06,0.68
6,7,4.6,3.4,1.4,0.3,Iris-setosa,15.64,0.42
7,8,5.0,3.4,1.5,0.2,Iris-setosa,17.00,0.30
8,9,4.4,2.9,1.4,0.2,Iris-setosa,12.76,0.28
9,10,4.9,3.1,1.5,0.1,Iris-setosa,15.19,0.15

There isn't anything else that really needs to be done and theres no other useful features to derive. You could reformat the species to be a '1, 2, 3' or 'a, b, c' but I don't it's feel necessary.

We'll inspect the cleaning before loading this dataframe into seperate .csv.

In [9]:
# Simple copy/paste from above

print("Initial shape:", df_raw.shape)
print('=' * 50)
print("Data types:\n", df_raw.dtypes)
print('=' * 50)
print("missing value count:\n", df_raw.isnull().sum())
print('=' * 50)
print("Duplicates count:\n", df_raw.duplicated().sum())
print('=' * 50)
df_raw.describe()

Initial shape: (150, 8)
==================================================
Data types:
 Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
SepalArea        float64
PetalArea        float64
dtype: object
==================================================
missing value count:
 Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
SepalArea        0
PetalArea        0
dtype: int64
==================================================
Duplicates count:
 0
==================================================

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,SepalArea,PetalArea
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667,17.806533,5.793133
std,43.445368,0.828066,0.433594,1.764420,0.763161,3.368693,4.713499
min,1.000000,4.300000,2.000000,1.000000,0.100000,10.000000,0.110000
25%,38.250000,5.100000,2.800000,1.600000,0.300000,15.645000,0.420000
50%,75.500000,5.800000,3.000000,4.350000,1.300000,17.660000,5.615000
75%,112.750000,6.400000,3.300000,5.100000,1.800000,20.325000,9.690000
max,150.000000,7.900000,4.400000,6.900000,2.500000,30.020000,15.870000

In [12]:
# We're now getting duplicates due to the new columns, not an issue.

print("Duplicates: ",df_raw["SepalArea"].duplicated().sum())
print("Duplicates: ",df_raw["PetalArea"].duplicated().sum())

# You can see the first two rows have a petal area of '0.27999999999999997'
df_raw.head()

Duplicates:  41
Duplicates:  49

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,SepalArea,PetalArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85,0.28
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70,0.28
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04,0.26
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26,0.30
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00,0.28

---

# Section 3 - Loading

In [15]:
# Saving as a new file 
#Copying the worked dataframe
df_cleaned = df_raw 

# Check the copy
print(df_cleaned.head())

# Exporting to folder 
df_cleaned.to_csv("Dataset/Cleaned/IrisCLeaned.csv",index=False)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

   SepalArea  PetalArea
0      17.85       0.28
1      14.70       0.28
2      15.04       0.26
3      14.26       0.30
4      18.00       0.28

# EDA in the next notebook.